/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        mulish: ["Mulish", "sans-serif"],
      },
      fontSize: {
        "heading-xlarge": ["28px", { lineHeight: "37px" }],
        "heading-large": ["24px", { lineHeight: "34px" }],
        "heading-medium": ["18px", { lineHeight: "27px" }],
        "subheading": ["16px", { lineHeight: "24px" }],
        "body": ["14px", { lineHeight: "22px" }],
        "caption": ["12px", { lineHeight: "19px" }],
        "xsmall": ["11px", { lineHeight: "16px" }],
        "button-big": ["16px", { lineHeight: "24px" }], 
        "button-small": ["14px", { lineHeight: "22px" }],
        "indicator": ["10px", { lineHeight: "19px" }],
        "hp-value-sm": ["14px", { lineHeight: "22px" }],
        "hp-value-md": ["20px", { lineHeight: "27px" }],
      },
      fontWeight: {
        bold: "700",
        medium: "500",
        regular: "400",
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
          50: "#EBEFF6",
          100: "#B1BDDB",
          200: "#E3E6E9",
          300: "#3B5AA6",
          400: "#293F74",
          500: "#182442",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        neutrals: {
          white: "#FFFFFF",
          50: "#F6F6F6",
          100: "#F2F5F7",
          200: "#A8AEB5",
          300: "#5A6066",
          400: "#44484C",
          500: "#2D3033",
          600: "#71787F",
          700: "#313336",
        },
        "hp-icon": "#F3F3F3",
        "pokemon-avatar-bg": "#EBEFF699",
        extended: {
          purple: {
            DEFAULT: "#A88FEF",
            hover: "#C0B0F2",
          },
          lightgreen: {
            DEFAULT: "#A7EF8F",
            hover: "#C2EFB8",
          },
          yellow: {
            DEFAULT: "#EAEB8F",
            hover: "#EBEFBD",
          },
          pink: {
            DEFAULT: "#EF8FBD",
            hover: "#EEA7CC",
          },
        },
        "success-green": "#51FF4E",
        "warning-yellow": "#FFF94E",
        "error-red": "#FF3131",
        gradient: {
          default: "linear-gradient(to right, #5BE2F7, #50DDA0)",
          disabled: "linear-gradient(to right, #5BE2F7, #50DDA0)",
          fainted: "linear-gradient(to right, #F75B5B, #DD7150)",
        },
        blue: {
          50: "#DFE9FF",
          500: "#6890F0",
        },
        red: {
          50: "#FFDFDF",
          100: "#FFDEDE",
          200: "#FFE4F8",
          500: "#F25D5B",
          600: "#C03028",
          700: "#F8383B",
        },
        green: {
          50: "#F0FFED",
          100: "#F5F7DF",
          500: "#41A83F",
          600: "#95A413",
        },
        yellow: {
          50: "#FFF9DF",
          100: "#FFF3DF",
          200: "#F5F0DF",
          500: "#C79B23",
          600: "#B6922E",
          700: "#B0982F",
        },
        purple: {
          50: "#E2DFFF",
          100: "#EBE8FF",
          200: "#E5DFEF",
          500: "#683FA8",
          600: "#9778F3",
          700: "#705898",
          800: "#6563CC",
        },
        pink: {
          50: "#FFE5ED",
          100: "#FFE8ED",
          500: "#F85888",
          600: "#DB5371",
        },
        gray: {
          50: "#F0F0E8",
          100: "#ECECF0",
          200: "#EEE5E0",
          500: "#A8A878",
          600: "#705848",
        },
        teal: {
          50: "#E8F8F8",
          500: "#38B4B4",
        },
      },
      backgroundImage: {
        "gradient-default": "linear-gradient(to right, #5BE2F7, #50DDA0)",
        "gradient-disabled": "linear-gradient(to right, #5BE2F7, #50DDA0)",
        "gradient-fainted": "linear-gradient(to right, #F75B5B, #DD7150)",
      },
      spacing: {
        "button-px": "16px",
        "button-py-sm": "9px",
        "button-py-md": "10px",
        "button-py-lg": "12px",
        "button-height-sm": "32px",
        "button-height-md": "36px",
        "button-height-lg": "40px",
        "gap-button": "4px", 
        "spinner-size-sm": "16px",
        "spinner-size-md": "24px",
        "spinner-size-lg": "32px",
        "hp-badge-height-sm": "14px",
        "hp-badge-height-md": "22px",
        "hp-badge-px-sm": "3px",
        "hp-badge-px-md": "4px",
        "hp-badge-gap-sm": "4px",
        "hp-badge-gap-md": "4px",
        "pokemon-name-gap-text": "16px",
        "pokemon-name-gap-icon": "8px",
        "table-header-height": "48px",
        "table-row-height": "72px",
        "table-cell-padding": "16px",
        "table-name-column-width": "300px",
        "table-description-max-width": "450px",
        "table-pagination-height": "44px",
        "table-pagination-padding": "10px",
        "dropdown-menu-gap": "2px",
        "dropdown-item-px": "12px",
        "dropdown-item-py": "6px",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        button: "4px",
        "hp-icon-sm": "9.75px",
        "hp-icon-md": "13px",
      },
      borderWidth: {
        "hp-icon-sm": "1.5px",
        "hp-icon-md": "2px",
        dropdown: "4px",
      },
      height: {
        'input': '2.375rem',
        'table-header-height': '48px',
        'table-row-height': '72px',
      },
      width: {
        'icon-size-sm': '1rem',   
        'icon-size-md': '1.25rem', 
        'icon-size-lg': '1.5rem',
        'icon-size-auto': '1em',  
        'hp-icon-sm': '14px',
        'hp-icon-md': '20px',
        'image-size-xs': '28px',
        'image-size-sm': '48px',
        'image-size-md': '54px',
        'image-size-lg': '80px',
        'table-name-column-width': '300px',
        'table-description-max-width': '450px',
      },
      height: {
        'icon-size-sm': '1rem',  
        'icon-size-md': '1.25rem', 
        'icon-size-lg': '1.5rem',
        'icon-size-auto': '1em',  
        'hp-icon-sm': '14px',
        'hp-icon-md': '20px',
        'image-size-xs': '28px',
        'image-size-sm': '48px',
        'image-size-md': '54px',
        'image-size-lg': '80px',
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}

